from docx.shared import RGBColor
from docx.oxml import OxmlElement, ns
from docx.shared import Inches, Pt, Cm

def header(vAR_new_doc):
    logo_path = 'image/ds.png'    # Path of the image file
    section = vAR_new_doc.sections[0]   # Create a section
    sec_header = section.header   # Create header 
    header_tp = sec_header.add_paragraph()  # Add a paragraph in the header, you can add any anything in the paragraph
    header_run = header_tp.add_run()   # Add a run in the paragraph. In the run you can set the values 
    header_run.add_picture(logo_path, width=Inches(1.3))  # Add a picture and set width.
    #rml_header = "\t Applied Artificial Intelligence for Schools Content \t Generation by Topic \t"
    headr =" "+"Content Generated by ChatGPT"
    header_run.add_text("\n                                                                                                        ")
#    header_run.add_text("Applied Artificial Intelligence for Schools Content Generation by Topic")
    header_run.add_text(headr)
    header_run.add_text("\n_______________________________________________________________________________________")
    header_run.font.size =  Pt(13)
    header_run.font.color.rgb = RGBColor(0, 0, 0)
    header_run.font.bold = True


    vAR_new_doc.add_paragraph('')