from docx.shared import RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.oxml import OxmlElement, ns
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn 
import os
import docx   
import source.page_num as pages

def heading_content_que_gen(vAR_new_doc,fin_txt,vAR_input_quetype):
    ##################### To add Title Page ###############################################    
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    vAR_new_doc.add_paragraph("")
    p=vAR_new_doc.add_paragraph()
    p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r=p.add_run("Question Generated by ChatGPT\n(Based On User Provided Input)\n"+vAR_input_quetype)
    r.font.size = Pt(24)
    r.bold = True
    r.underline = True
    r.font.color.rgb = RGBColor(0, 0, 153)
    vAR_new_doc.add_page_break()


    headx=vAR_new_doc.add_heading(vAR_input_quetype)
    headx.style.font.color.rgb = RGBColor(0, 0, 139)
    headx.style.font.size = Pt(14)
    headx.style.font.bold = True
    headx.style.font.all_caps = True
    vAR_new_doc.add_paragraph(fin_txt)
    ##################### To add logo - 3rd Document ###############################################


    logo_path = 'image/ds.png'    # Path of the image file
    section = vAR_new_doc.sections[0]   # Create a section
    sec_header = section.header   # Create header 
    header_tp = sec_header.add_paragraph()  # Add a paragraph in the header, you can add any anything in the paragraph
    header_run = header_tp.add_run()   # Add a run in the paragraph. In the run you can set the values 
    header_run.add_picture(logo_path, width=Inches(1.3))  # Add a picture and set width.
    #rml_header = "\t Applied Artificial Intelligence for Schools Content \t Generation by Topic \t"
    headr =" "+"Questions Generated by ChatGPT "
    header_run.add_text("\n                                                                                                        ")
    #    header_run.add_text("Applied Artificial Intelligence for Schools Content Generation by Topic")
    header_run.add_text(headr)
    header_run.add_text("\n_______________________________________________________________________________________")
    header_run.font.size =  Pt(13)
    header_run.font.color.rgb = RGBColor(0, 0, 0)
    header_run.font.bold = True


    vAR_new_doc.add_paragraph('')
    #--------------------------------------------

    ##################### To add footer with page number - 3rd Document ###############################################


    section = vAR_new_doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = "_________________________________________________________________________________ \t \n\n © DeepSphere.AI | Confidential and Proprietary |Not for Distribution \t"
    pages.add_page_number(vAR_new_doc.sections[0].footer.paragraphs[0])
    return vAR_new_doc